### ISSUE TITLE
Linking failing on darwin

### ISSUE THREAD

**Issue by cmacrae** [serokell/deploy-rs#132] opened 2021-09-27 21:38 UTC
Hey 👋 

It seems building on x86_64-darwin systems is broken. Here's the error output from  
`nix build -L github:serokell/deploy-rs#defaultPackage.x86_64-darwin`:
```
deploy-rs>   = note: ld: framework not found SystemConfiguration
deploy-rs>           clang-7: error: linker command failed with exit code 1 (use -v to see invocation)
deploy-rs>           
deploy-rs> error: aborting due to previous error
deploy-rs> error: build failed
error: builder for '/nix/store/9qi7s1m3dpfikbrcamqy0ivlglf420r1-deploy-rs-0.1.0.drv' failed with exit code 101;
       last 10 log lines:
       > error: linking with `/nix/store/3v5asy4nb2yqkb3asgvpv6ya7nzh09yh-clang-wrapper-7.1.0/bin/cc` failed: exit status: 1

```

Any ideas?

**Comment by balsoft** [comment] 2021-09-28 09:41
I can reproduce. Not sure when it broke, since it was fixed once already here: https://github.com/serokell/deploy-rs/commit/42cbe751a860470cc8fd36f9e105566b97b6a2ff

**Comment by balsoft** [comment] 2021-09-28 09:52
Thanks for reporting the issue!

**Closed** 2021-09-28 09:52 UTC

**Comment by cmacrae** [comment] 2021-09-28 09:53
Ah great! Thanks for such a quick turn around on fixing it @balsoft 🙇
