### ISSUE TITLE
Hostnames with . in them have weird results

### ISSUE THREAD

**Issue by antifuchs** [serokell/deploy-rs#10] opened 2020-11-25 03:44 UTC
I thought I'd define my nixos config entries to be the same as the FQDN of the hosts that I'm deploying to - but apparently deploy-rs uses `.` as a separator between the hostname and a profile name:

```
$ nix run github:serokell/deploy-rs ./#monitor.example.com
[...]
 ERROR deploy > Failed to deploy all profiles: example.com
```

I assume the `.` separates hosts from deploy profiles; is there a better way to do that? I think FQDNs would be really useful for identifying larger sets of hosts, making the dot character quite valuable.

**Comment by notgne2** [comment] 2020-11-25 05:16
That's actually the wrong error message entirely so I've fixed that now, it should actually be saying that there is no profile found named `example.com`. As for the actual issue that's an interesting question, our naming scheme at Serokell hasn't caused us to run into this yet but it's something we'd like to support, I'll have to think about the best way to handle it

**Comment by antifuchs** [comment] 2020-11-25 15:16
Thanks for the fix - I have been thinking about this and maybe `/` could be used to separate the hostname from the profile name in the flake fragment?

**Comment by balsoft** [comment] 2020-11-25 22:44
Is there a reason to use FQDN instead of just the host name (i.e. `monitor.example.com` instead of just `monitor`)?

**Comment by notgne2** [comment] 2020-11-27 22:44
As seen in the issue closed in favor of this one above (#15), even if we fix our _own_ parsing, we are still going to run into similar issues with Nix itself.

In the above case it was us passing the expression to build profile path to `nix build`, and there appears to be no way to escape there, so we'll need to figure out a way around that (the obvious choice of `nix build --exp` needs `--impure` for `builtins.getFlake` to work it seems)

**Comment by notgne2** [comment] 2020-11-28 01:53
Ok, that part was surprisingly easy to solve, I was almost certain earlier that this didn't work

**Comment by notgne2** [comment] 2020-11-28 02:07
Alright, is this satisfactory @antifuchs ? it will use the last `.` for separation and ignore the trailing `.`. The command that you last used still won't work, but `nix run github:serokell/deploy-rs ./#monitor.example.com.` _will_, additionally `nix run github:serokell/deploy-rs ./#monitor.example.com.system` should work too (at least in theory).

**Comment by antifuchs** [comment] 2020-11-28 04:11
Huh! That's a really neat solution. I like it - I'll try this out and report back (:

**Comment by notgne2** [comment] 2020-11-29 18:53
I've changed this again now in https://github.com/serokell/deploy-rs/commit/fa4c0a86cd608f5e98b50e8eb4b03db04a7726ce, it's not exactly Nix parity though it's a lot more like it, so should be a lot more expected

(tl;dr, put things in quotation marks)

**Comment by zhenyavinogradov** [comment] 2020-11-30 05:14
One solution to escaping issues is to use separate arguments for the node and the profile, e.g. `deploy --flake . --node example.com --profile system`

**Comment by notgne2** [comment] 2020-12-02 17:28
@zhenyavinogradov that would work, though it's longer (and kinda boring), as of my latest change to use a Nix parser I don't think we have a problem anymore (you can do `deploy .#"example.com".system`), though I'm keeping this issue open until we document this being the case (and make sure there are no more weird issues elsewhere).

**Closed** 2021-01-25 01:54 UTC
Labels: bug

**Comment by Sohalt** [comment] 2022-07-14 14:03
This still fails if you try to do `deploy .#example.com` (where the profile should be taken from the `deploy.nodes` config).

**Comment by balsoft** [comment] 2022-07-14 14:10
Try `deploy '.#"example.com"'`

**Comment by Sohalt** [comment] 2022-07-14 14:22
Sorry, I meant to write `deploy .#\"example.com\"` (which as far as shell escaping goes should be equivalent to `'.#"example.com"'`.
The problem is that `first_child.children_with_tokens()` in https://github.com/serokell/deploy-rs/blob/184349d8149436748986d1bdba087e4149e9c160/src/lib.rs#L208 parses as `TOKEN_STRING_START`, `TOKEN_STRING_CONTENT`, `TOKEN_STRING_END`, which triggers `ParseFlakeError::Unrecognized`.

Adding a trailing `.` like `deploy .#\"example.com\".` works as a workaround.
