### ISSUE TITLE
Terminal becomes slow while waiting for activation

### ISSUE THREAD

**Issue by luizribeiro** [serokell/deploy-rs#137] opened 2021-11-16 14:07 UTC
This is a weird one, so apologies in advance for the not so great bug report. Hopefully this rings a bell to someone.

When my deployment hits an error and it rolls back, my ssh connection becomes extremely slow - to the point I need to press the same key multiple times.

This all goes back to normal when this shows up:

```
👀 ❌ [wait] [ERROR] Error waiting for activation: Timeout elapsed for confirmation
```

Here's an example session:

```
...
⭐ ⚠️ [activate] [WARN] De-activating due to error
switching profile from version 16 to 15
⭐ ⚠️ [activate] [WARN] Removing generation by ID 16
removing profile version 16
⭐ ℹ️ [activate] [INFO] Attempting to re-activate the last generation
activating the configuration...
reloading user units for luiz...
setting up tmpfiles
⭐ ❌ [activate] [ERROR] The activation script resulted in a bad exit code: Some(4)
🚀 ❌ [deploy] [ERROR] Activating over SSH resulted in a bad exit code: Some(1)
🚀 ℹ️ [deploy] [INFO] Revoking previous deploys
luiz@carbon nixos % # everything here is suuuuper slow
luiz@carbon nixos % # and it takes some time to get away from it, it only gets back to normal after the timeout:
👀 ❌ [wait] [ERROR] Error waiting for activation: Timeout elapsed for confirmation
luiz@carbon nixos % # back to normal
```

**Comment by aaronjanse** [comment] 2021-11-22 04:21
> to the point I need to press the same key multiple times

Ooh, this might be caused by a background process still reading from /dev/stdin after the foreground process exits. The end result would be ~half of keypresses being sent to the background process and the other half being sent to your interactive shell

**Comment by aaronjanse** [comment] 2021-11-22 04:25
Oh ha yep, this seems to be a dupe of https://github.com/serokell/deploy-rs/issues/105, to be fixed by https://github.com/serokell/deploy-rs/pull/138

**Comment by notgne2** [comment] 2021-12-05 00:57
Guess I'll close this now that it's merged, hopefully won't be an issue again

**Closed by notgne2** 2021-12-05 00:57 UTC

**Comment by luizribeiro** [comment] 2021-12-11 18:35
@notgne2, I'm still able to repro this as of 715e92a13018bc1745fb680b5860af0c5641026a

Is it possible this was a separate issue from #105?
