### ISSUE TITLE
does not provide attribute 'packages.x86_64-linux.deploy.nodes.laptop.nix.profiles.system.path', 'legacyPackages.x86_64-linux.deploy.nodes.laptop.nix.profiles.system.path' or 'deploy.nodes.laptop.nix.profiles.system.path'

### ISSUE THREAD

**Issue by bbigras** [serokell/deploy-rs#15] opened 2020-11-27 18:46 UTC
Not sure what I'm doing wrong.

Here's my https://github.com/bbigras/nix-config/blob/ec185dc51b4818c154cdd6d88a0c0080f3000a71/flake.nix .

Note that I'm using a nix file for each system instead of a directory with a default.nix.

```
[bbigras@desktop:~/nix-config]$ deploy
 INFO  deploy > Running checks for flake in .
warning: Git tree '/home/bbigras/nix-config' is dirty
warning: unknown flake output 'deploy'
 INFO  deploy > Evaluating flake in .
warning: Git tree '/home/bbigras/nix-config' is dirty
 WARN  deploy > The following profiles are going to be deployed:
["laptop.nix".system]
user = "root"
ssh_user = "bbigras"
path = "/nix/store/5q9256z5p4fxqksq4mqj44j7rf02ngn6-activatable-nixos-system-laptop-21.03.20201121.2247d82"
hostname = "laptop"
ssh_opts = []

 INFO  deploy::utils::push > Building profile `system` for node `laptop.nix`
warning: Git tree '/home/bbigras/nix-config' is dirty
error: --- Error --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- nix
flake 'git+file:///home/bbigras/nix-config' does not provide attribute 'packages.x86_64-linux.deploy.nodes.laptop.nix.profiles.system.path', 'legacyPackages.x86_64-linux.deploy.nodes.laptop.nix.profiles.system.path' or 'deploy.nodes.laptop.nix.profiles.system.path'
 ERROR deploy              > Failed to push profile: Nix build command resulted in a bad exit code: Some(1)
```

Also it's weird that I can't run `nix run github:serokell/deploy-rs`. I'm using a `nix develop` shell instead:

```
❯ nix run github:serokell/deploy-rs                                                                                                                                                                     nix-shell
error: --- UsageError ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- nix
unrecognised flag '--command'
Try 'nix --help' for more information.
```

**Comment by notgne2** [comment] 2020-11-27 22:00
Huh, that's interesting that the evaluation stage completed though building fails. Is there a `default.nix` anywhere? I don't see one in your Git repo, but if there was one there is a chance it might confuse Nix as it's never explicitly told to use the Flake.

For the `nix run` issue I can replicate that too and will look into that

**Comment by notgne2** [comment] 2020-11-27 22:08
Actually scratch that, the `nix run` error I had was different and my own mistake

**Comment by notgne2** [comment] 2020-11-27 22:11
@bbigras figured it out, this is an escaping issue. Your laptop's hostname isn't `laptop` it's `laptop.nix`, which is causing it to fail as when it is given to `nix build` in the form `${flake}#deploy.nodes.${nodeName}.profiles.${profileName}.path`, it will be `.#deploy.nodes.laptop.nix.profiles.system.path`, which is _not_ the actual location of it, and will thus fail.

**Comment by notgne2** [comment] 2020-11-27 22:41
Actually, I think this counts as a duplicate of #10 , as it is a weird result from the same cause. The `nix run` issue appears to be unrelated and I can't replicate it, feel free to open a separate issue for that.

**Closed by notgne2** 2020-11-27 22:41 UTC

**Comment by bbigras** [comment] 2020-11-28 02:10
Thanks!
