### ISSUE TITLE
Activation script runs forever

### ISSUE THREAD

**Issue by lovesegfault** [serokell/deploy-rs#32] opened 2020-12-19 05:00 UTC
Even after the deploy has been successful and my `deploy .#myHost` command has exited, I can see the activation script running on my machine and pegging one CPU on 100% utilization.
```
❯ ps aux | rg -i deploy-rs
root     18497  100  0.0 953168   608 ?        Sl   20:57   0:41 /nix/store/5sdsrjrk314jv8zw8179bl65bkcg3dim-deploy-rs-0.1.0/bin/activate /nix/var/nix/profiles/system /nix/store/m8cv0h46jl4krqvwhf469561c3mlv1xs-activatable-nixos-system-foucault-21.03.20201218.9e67377 --temp-path /tmp --confirm-timeout 30 --magic-rollback --auto-rollback
bemeurer 18988  0.0  0.0   9700  4556 pts/2    R+   20:58   0:00 rg -i deploy-rs
```

This happens every single time I deploy to my machine.

**Comment by notgne2** [comment] 2020-12-19 07:21
Can you try running it with `--magic-rollback false` and see if this still happens?

**Comment by lovesegfault** [comment] 2020-12-20 00:31
Yeah, I can confirm the issue does _not_ happen if I disable magic rollback. And I can also reproduce it _every_ time I do a deploy _with_ magic rollback.

**Comment by lovesegfault** [comment] 2020-12-20 00:40
Actually, scratch that, seems like I just had it not happen. The deploy immediately after it, though, reproduced the problem again.

**Comment by antifuchs** [comment] 2020-12-21 05:39
@lovesegfault can you confirm that this happens on ba7f57086c41e5094f880e9bb7a117861bb4df5a as well as latest HEAD? I recently changed the activate script's magic rollback functionality, and while I see it work for me, I'm curious if that's what broke it for you...

**Comment by kraem** [comment] 2020-12-21 12:09
I'm having the same problem on 91e934fd9e1e06044f75a3e3ad998813c2a90fb5.

Having another issue with `magicRollback` where the `sshUser` is in group `wheel`. It asks for my sudo password like it should  but fails immediately after:
```
 INFO  deploy::utils::deploy > Success activating!
 INFO  deploy::utils::deploy > Attempting to confirm activation
sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
sudo: a password is required
 ERROR deploy                > Failed to deploy profile: Confirming activation over SSH resulted in a bad exit code (the server should roll back): Some(1)
``` 
Would this be a misconfiguration or a bug? I'm open to open another issue if this is the wrong forum..

**Comment by antifuchs** [comment] 2020-12-21 17:15
> I'm having the same problem on 91e934f.

Phew - sounds like this is unrelated to my change, then. Thanks for confirming!

**Comment by lovesegfault** [comment] 2020-12-22 03:24
I have passwordless sudo on all my systems, so I would be surprised if #36 were to solve this problem.

**Comment by kraem** [comment] 2020-12-22 07:46
@lovesegfault Sorry if I was unclear; that issue was unrelated, this issue still remains.

**Comment by lovesegfault** [comment] 2020-12-22 07:48
> @lovesegfault Sorry if I was unclear; that issue was unrelated, this issue still remains.

Ah, I see :)

I'm also not convinced using a pseudo terminal is correct. I feel like the right thing for the tool to do when faced with a sudo prompt is to fail immediately. It's weird, IMO, for a deployment tool to ask for input.

It either has the correct perms or it doesn't.

**Comment by kraem** [comment] 2020-12-22 07:56
It still doesn't affect use cases where the user have the "correct" perms. Adding, and having, the possibility to have password prompts for users in `wheel` adds an extra layer of security, but maybe using a pseudo terminal increases the attack vector somehow?

**Comment by lovesegfault** [comment] 2020-12-22 08:11
NB: I have written absolutely 0 lines of code for this project, and so my opinion here is worth almost nothing; I'm just sharing it in case it's useful and as a user who's interested

---

> It still doesn't affect use cases where the user have the "correct" perms. Adding, and having, the possibility to have password prompts for users in `wheel` adds an extra layer of security, but maybe using a pseudo terminal increases the attack vector somehow?

My concern here isn't about the attack vector, but more behavior expectations. Imagine, for example, that I set my CI up so that after successful build it deploys to my system (CD sort of thing).

If I mis-configure something so that the tool can no longer raise perms to sudo without input, what should I expect happen:
1. My CD pipeline gets stuck there forever, until I realize and go stop it
2. The tool fails immediately

I, personally, expect 2. to happen. I believe with the advent of SSH keys there should be _no_ scenario where you need password input to deploy to a system.

If you want to have `sudo` with password for your user, then create a `deploy-rs` user with passwordless sudo and use that one for deployment instead.

**Comment by kraem** [comment] 2020-12-22 08:27
Valid point. I didn't write any code for the project either. I have a separate user set up for deploying, but I was just curious about the security implications about going passwordless :)

**Comment by notgne2** [comment] 2020-12-30 23:06
I've been looking into this (and #38, though I had less luck reproducing that one), and I think it's almost certainly because of a weird hack I employed to make the activation script fork into the background for the magic_rollback handling.

I'm rewriting this logic to no longer require a fork/daemonization so this issue should go away (basically, don't bother trying to find a workaround fix, I'm deleting all the offending code)

**Comment by notgne2** [comment] 2021-01-08 21:59
This should be fixed now that https://github.com/serokell/deploy-rs/pull/40 has merged, I've been able to reproduce it in the past but I can't anymore with those new changes, if you still have issues let me know so I can re-open this

**Closed by notgne2** 2021-01-08 21:59 UTC
Labels: bug
