### ISSUE TITLE
Likely confusion between target system & system running deploy

### ISSUE THREAD

**Issue by antifuchs** [serokell/deploy-rs#13] opened 2020-11-25 22:16 UTC
I finally got to the "activate" stage in my porting to deploy-rs (while running deploy on my macOS Big Sur machine), and unfortunately the deploy failed with:

```
 INFO  deploy > Evaluating flake in ./
 WARN  deploy > The following profiles are going to be deployed:
[monitor.system]
user = "root"
ssh_user = "asf"
path = "/nix/store/rscx6ya03wvd4qj2vv80pz1kazw7whrh-activatable-nixos-system-monitor-21.03.20201121.1ffd7cf"
hostname = "monitor.example.com"
ssh_opts = []

 INFO  deploy::utils::push > Building profile `system` for node `monitor`
warning: Git tree '/Users/asf/home' is dirty
 INFO  deploy::utils::deploy > Activating profile `system` for node `monitor`
sudo: /nix/store/n8hj08m4n6bwbvdm92ka59rjmaz29hvg-deploy-rs-0.1.0/bin/activate: command not found
Connection to monitor.example.com closed.
 ERROR deploy                > Failed to deploy profile: Activation over SSH resulted in a bad exit code: Some(1)
```

What's more, the closure that lands on the linux machine, printed above (`/nix/store/n8hj08m4n6bwbvdm92ka59rjmaz29hvg-deploy-rs-0.1.0/bin/`) contains a `deploy` binary that's built for macOS.

My guess is that the closure that gets copied to the target machine is compiled for the machine running the deploy. Maybe there's one more thing that needs building with the correct target platform set.

**Comment by antifuchs** [comment] 2020-11-25 22:34
oh, just in case it's unclear, I am using the `x86_64-linux` platform activate function:

``` nix
    deploy = {
      nodes = {
        "monitor" = {
          hostname = "monitor.example.com";

          profiles.system = {
            path = deploy-rs.lib.x86_64-linux.activate.nixos self.nixosConfigurations."monitor";
          };
        };
    };
```

**Comment by balsoft** [comment] 2020-11-25 22:42
Ah, yes, right. @notgne2 how about we choose and ship the `activate` binary in the `activate.custom` function instead of doing so at runtime?

**Comment by antifuchs** [comment] 2020-11-25 22:43
Traced this down into the guts of the deploy sources (https://github.com/serokell/deploy-rs/blob/3da8c6d048be03ecaf5caa54d945740ab88be465/src/utils/mod.rs#L165-L166), where we take the currently-running executable, which isn't guaranteed to work on the target.

**Comment by balsoft** [comment] 2020-11-25 22:46
This is a remnant of the old prototype which was intended to be usable without adding it as a dependency to the flake defining the servers. Now that we have to use `deploy-rs.lib.${system}.activate` anyways, I suppose it's better to choose the binary there.

**Comment by antifuchs** [comment] 2020-11-26 00:02
Makes perfect sense! I think I have a prototype change that might fix this. Will submit a draft PR in a moment.

**Comment by notgne2** [comment] 2020-12-02 17:25
I believe this should be fixed now

**Closed by notgne2** 2020-12-02 17:25 UTC
Labels: bug
