### ISSUE TITLE
Default boot entry is never updated

### ISSUE THREAD

**Issue by lovesegfault** [serokell/deploy-rs#31] opened 2020-12-19 02:32 UTC
If I look at my system profiles I see this:
```
❯ ls /nix/var/nix/profiles
Permissions Size User Date Modified Name
lrwxrwxrwx    15 root 14 Dec 18:01  default -> default-87-link
lrwxrwxrwx    60 root 14 Dec  7:37  default-87-link -> /nix/store/nivqnkygpax10ph1s2f5m8km4nr8sc24-user-environment
drwxr-xr-x     - root  4 Jun  1:27  per-user/
lrwxrwxrwx    15 root 18 Dec 18:12  system -> system-434-link
lrwxrwxrwx   100 root 18 Dec 17:28  system-432-link -> /nix/store/nzd9if3g1m1z2b37694pkq3472mdrhnx-activatable-nixos-system-foucault-21.03.20201218.9e67377
lrwxrwxrwx   100 root 18 Dec 17:46  system-433-link -> /nix/store/yycw0bmzpi7l5bx5zkpk4nb79sfydyki-activatable-nixos-system-foucault-21.03.20201218.9e67377
lrwxrwxrwx   100 root 18 Dec 18:12  system-434-link -> /nix/store/m8cv0h46jl4krqvwhf469561c3mlv1xs-activatable-nixos-system-foucault-21.03.20201218.9e67377
```

This looks exactly right, my last system profile, 434, was a successful deploy and so `/nix/var/nix/profiles/system` points to it.

If, now, I go look at my bootloader (systemd-boot) config, I see this:
```
❯ cat /boot/loader/loader.conf
───────┬──────────────────────────────────────────────────
       │ File: /boot/loader/loader.conf
───────┼──────────────────────────────────────────────────
   1   │ timeout 2
   2   │ default nixos-generation-426.conf
   3   │ console-mode keep
───────┴──────────────────────────────────────────────────
```

And this is despite the fact that the correct generation _is_ available in the boot partition 
```
❯ ls /boot/loader/entries
Permissions Size User Date Modified Name
.rwxr-xr-x   748 root 18 Dec 18:12  nixos-generation-432.conf*
.rwxr-xr-x   748 root 18 Dec 18:12  nixos-generation-433.conf*
.rwxr-xr-x   748 root 18 Dec 18:12  nixos-generation-434.conf*
```

The current default happened right around the same time I switched to deploy-rs. Could it be that it's just not updating that parameter?

**Comment by lovesegfault** [comment] 2020-12-19 06:38
This can be worked around by just manually deleting the `default` line in the `loader.conf` of each machine.

**Comment by notgne2** [comment] 2020-12-19 07:20
That's annoying, though I'm glad somebody was able to reproduce this issue. I've had this on a few of my local machines on and off (it seems to work sometimes), though nobody else has reported the same issue (until now). I wonder what deploy-rs is doing differently to `nixos-rebuild switch` which makes it not work? The bootloader entries consistently show up every time, though will not be made the default, I would've expected the logic for this to be within `switch-to-configuration` which deploy-rs does use too.

**Comment by Infinisil** [comment] 2020-12-19 12:16
In Nixus I use this to set the default system profile, after which `switch-to-configuration boot` is ran, which creates the boot entries accordingly: https://github.com/Infinisil/nixus/blob/master/scripts/switch#L141

**Comment by notgne2** [comment] 2020-12-19 17:55
Unless I'm missing something, I'm doing approximately the same thing here https://github.com/serokell/deploy-rs/blob/master/src/activate.rs#L285-L318 - it sets the `system` profile to be the new system, then uses the path to it to run `switch-to-configuration`

**Comment by notgne2** [comment] 2020-12-19 23:02
Also worth noting, it looks like it has never worked on my PC at all, I only boot correctly because the default boot option in fact does not exist
![image](https://user-images.githubusercontent.com/28779487/102701368-96fe6b80-4213-11eb-8c77-0718fe7844f4.png)

**Comment by lovesegfault** [comment] 2020-12-20 00:00
> Also worth noting, it looks like it has never worked on my PC at all, I only boot correctly because the default boot option in fact does not exist
> ![image](https://user-images.githubusercontent.com/28779487/102701368-96fe6b80-4213-11eb-8c77-0718fe7844f4.png)

Right, on this machine things were working b/c the default option didn't exist. I noticed this because on another machine the listed default _did_ exist and whenever I'd reboot I saw things revert to an older state and was confused.

**Comment by kraem** [comment] 2020-12-22 07:49
Just to add a data point: Can confirm this happens to me too.

**Comment by antifuchs** [comment] 2020-12-22 17:47
I can confirm that this happens to me too with grub instead of the systemd loader.

One suspicious thing I saw trying to trace the layers of indirection here is [this line of code](https://github.com/serokell/deploy-rs/blob/master/flake.nix#L83) - what does `$PROFILE` there point to? Is it the currently-running one, maybe?

**Comment by antifuchs** [comment] 2020-12-22 18:10
Hm, no, that's not it - `$PROFILE` is set in [the activation code](https://github.com/serokell/deploy-rs/blob/master/src/activate.rs#L305) and so should be right.

The main difference between nixus & deploy-rs's behavior (afaict) is that nixus's flow is like this:

1. try running [`switch-to-configuration boot`](https://github.com/Infinisil/nixus/blob/master/scripts/switch#L140)
2. [set the profile with `nix-env --set`](https://github.com/Infinisil/nixus/blob/master/scripts/switch#L141)
3. [re-run `switch-to-configuration boot`](https://github.com/Infinisil/nixus/blob/master/scripts/switch#L146)

...and deploy-rs does:

1. [`nix-env --set`](https://github.com/serokell/deploy-rs/blob/master/src/activate.rs#L285)
2. [`switch-to-configuration switch`](https://github.com/serokell/deploy-rs/blob/master/src/activate.rs#L304) via the [generated deploy-rs-activate](https://github.com/serokell/deploy-rs/blob/master/flake.nix#L83) script
3. waits for activation.

The comment in nixus leads me to suspect that something weird is going on here: https://github.com/Infinisil/nixus/blob/master/scripts/switch#L142-L144

Further reproducing this, it doesn't look like any of my deploy-rs initiated deploys had any effect on the boot menu (neither the default config nor `system` profile generations, nor the past grub entries behind the menu); the only things I could find in there were pre-deploy-rs entries.

**Comment by notgne2** [comment] 2020-12-22 18:13
Maybe I should bring back my since-deleted `bootstrap` attribute then, because currently I don't think I made any way for deploy-rs to run things both before and after updating the profile, though I'm very confused why this is required for NixOS to work. Are there any other examples of this workaround in other tools (morph, etc)?

**Comment by antifuchs** [comment] 2020-12-22 18:21
Hm, looks like morph does the same thing deploy-rs does: https://github.com/DBCDK/morph/blob/c048d6339f18613a1544bc62ff852cb4c6de1042/ssh/ssh.go#L216-L251

1. `nix-env --set`
2. `switch-to-configuration <command>`

**Comment by notgne2** [comment] 2020-12-22 18:45
Here's the slight difference I realized (after doing activation manually and it working fine), every other tool sets `/nix/var/nix/profiles/system` to be a NixOS system closure, this actually isn't what `deploy-rs` does, `deploy-rs` sets it to be a custom one generated with `pkgs.buildEnv` (adding a copy of the `activate` binary and the `/deploy-rs-activate` script).

a normal path to set the profile to: `/nix/store/r98pw7vdlz8xbcgsc66rmkzgavjwkf50-nixos-system-peppaboned-21.03.20201209.e9158ec`
what `deploy-rs` sets: `/nix/store/djf8drf6gasxy488q1fr2bd4as90fr6g-activatable-nixos-system-peppaboned-21.03.20201209.e9158ec`

perhaps the GRUB updating logic attempts to parse the path/name somehow and is failing? or is something a symlink which shouldn't be

**Comment by notgne2** [comment] 2020-12-22 18:48
We also know that this issue happens if you activate before setting the profile, that's potentially what NixOS thinks is happening here

- activation script runs
- script checks if the system profile points to the version which you are running
- it isn't (as the system profile is a buildEnv with a symlink to the real profile)
- skips setting GRUB

**Comment by antifuchs** [comment] 2020-12-22 21:31
Hm, reading it a little more closely, I don't see the switch-to-configuration script bailing if anything is different: In fact, it should set up the bootloader config [before it even activates config for real](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/system/activation/switch-to-configuration.pl#L47-L49). (Also, it doesn't roll back if anything goes wrong with activation! I think that's one strike in favor of the nixus approach, which switches the currently-running config first, using `switch-to-configuration test`)

**Comment by balsoft** [comment] 2020-12-22 21:56
> (Also, it doesn't roll back if anything goes wrong with activation! I think that's one strike in favor of the nixus approach, which switches the currently-running config first, using switch-to-configuration test)

`deploy-rs` will also roll back if anything goes wrong and `autoRollback` is enabled.

**Comment by antifuchs** [comment] 2020-12-22 23:22
So - I had a weird run-in with this whole activation/switch-to-configuration mess. For context, the configuration I deploy includes a home-manager config as part of the system configuration, so it creates a per-user profile as well.

When I rolled a revision of my system configuration out, the deploy seems to have gone correctly (no error messages, exit status 0), but the per-user profile was still set to the previous config, as if it had been rolled back. Using `nix-env -p ... --set` and manually invoking `switch-to-configuration test` with the path that deploy-rs printed at the start of the deploy got me the configuration that I wanted. 

I'm not able to repro this at the moment, but this whole construction feels a little scary and brittle now.

**Comment by notgne2** [comment] 2020-12-23 01:00
@antifuchs I think auto rollback should catch any error, but I've been meaning to refactor `activate.rs` a little so it's more concise and easier to make sure we didn't miss anything, though I wouldn't mind having it run `test` first, that should work to be very protective along with `magicRollback`, but the only real cases this protects against is if a configuration crashes halfway through the activation process (after adding to the bootloader, but before activating), or if activation causes the machine to turn off (killing the background process for `magicRollback`)

**Comment by antifuchs** [comment] 2020-12-23 05:43
Agreed, @notgne2 - I think refactoring that function would make it much easier to get what's going on (the error handling makes it a bit unwieldy...) - and changing the procedure to be something like this should fix the bug:

1. with the "magicRollback" guard, do `switch-to-configuration test`
2. if that works, do `switch-to-configuration boot` once or twice, however many goes it needs
3. success (:

That might make the rollback a bit harder (not sure if the procedure to roll back from step 1 is the same as step 2), but it seems quite reasonable to emulate nixus here (:

**Comment by zhenyavinogradov** [comment] 2020-12-23 05:49
The idea of @notgne2 that switch-to-configuration checks that profile path is the same as original closure path is correct, systemd-boot activation script skips updating the default entry when they are different: https://github.com/NixOS/nixpkgs/blob/2ae527c50e049570dd25132f9325527aa2320e32/nixos/modules/system/boot/loader/systemd-boot/systemd-boot-builder.py#L226

**Comment by notgne2** [comment] 2020-12-23 05:52
@zhenyavinogradov good find, I must have missed that.

I'm actually pretty annoyed that this is the case, I don't see why that's needed, and if there is a good enough reason then I think activation should fail entirely, though this case might be (relatively) apparent and simple, it sets a bad precedent of NixOS allowing activations to half-succeed without erroring.

I guess we should be figuring out how to work around that now, though I imagine it won't be half as simple as just running `switch-to-configuration` twice

**Comment by notgne2** [comment] 2020-12-23 05:57
I guess the simplest fix would be if we can find a way to add the activate binary and `deploy-rs-activate` to the NixOS system derivation directly rather than in a second derivation, and not using `activate.custom` for it at all? I'm not sure if that's possible

**Comment by antifuchs** [comment] 2020-12-23 17:22
> I guess the simplest fix would be if we can find a way to add the activate binary and deploy-rs-activate to the NixOS system derivation directly rather than in a second derivation

Is there a way to find the original NixOS system derivation and pass that as an argument to the activate binary (as `$PROFILE`)?

**Comment by notgne2** [comment] 2020-12-23 19:53
I think the problem here is that if `deploy-rs-activate` isn't present in the profile itself, then we would have to assume that the activation command never changes, which is dangerous as you may modify it, fail a deployment, and then fail to roll back

**Comment by notgne2** [comment] 2020-12-23 21:21
Also, I've traced that check in the systemd boot module back to https://github.com/NixOS/nixpkgs/commit/02e209b139822ee64a55a0d8d04770f947a7d411 when the module was first added back in 2013, I wonder if NixOS would be open to removing it? As far as I know, the only purpose is so it can know which profile to make the default, but in theory that shouldn't be needed at all (maybe it was in 2013), it should just be able to get that information from the `/nix/var/nix/profiles/system` path (not `-n-link` like what gets iterated)

**Comment by antifuchs** [comment] 2020-12-24 17:27
> I think the problem here is that if deploy-rs-activate isn't present in the profile itself, then we would have to assume that the activation command never changes, which is dangerous as you may modify it, fail a deployment, and then fail to roll back

Hm, that's not quite what I proposed, I think: deploy-rs should act on (something like) the symlink farm constructed in that branch, but only pass the nixos system output to the switcher. Outside of the currently-running deploy process (to evaluate roll-forward success), you don't need the `deploy-rs-activate` script at all, so it should be safe to have the link farm be alive only during the roll-forward process.

I agree that nixpkgs's switch-to-configuration probably needs fixing, but am a little apprehensive about what that would mean for people running stable releases in the meantime: We wouldn't be able to roll out reboot-persistent changes until next May or June, most probably?

**Comment by notgne2** [comment] 2020-12-24 21:04
@antifuchs I'm not sure how to work around the rollback issue that way though, I think understand the concept, but if we set the system profile to be the raw profile itself (not augmented), then using `nix-env`'s rollback would not bring back the older version of `deploy-rs-activate` for us to use to re-activate the older generation, instead we would have the use the current deployment's version of `deploy-rs-activate` on the previous generation of the deployment, which could potentially cause issues if it was ever changed.

**Comment by antifuchs** [comment] 2020-12-24 23:21
Ohhhhh, ok, now I see: So I guess the only backward-compatible way to get it in there while also remaining compatible with the old version of installing the loader configs might be to have users install the activation scripts/binaries as part their nixos config, maybe provide a module that can be added in the flake's nixos config.

It's not ideal, but it might give us the desired effect without having to patch nixpkgs for now.

**Comment by balsoft** [comment] 2020-12-25 07:31
It's possible to "patch" the output of `nixosSystem` to include some modules in there, I believe. We can just do that, if we can figure out how to write to the root of the toplevel build.

**Comment by KyleOndy** [comment] 2020-12-31 17:20
> This can be worked around by just manually deleting the `default` line in the `loader.conf` of each machine.

I can confirm this work-around works for me.

**Comment by notgne2** [comment] 2021-01-05 21:01
huh, what if we work around this the ~~dumb~~ easy way, and have `activate.nixos` automatically write to `loader.conf` by itself

**Comment by balsoft** [comment] 2021-01-05 21:06
> have activate.nixos automatically write to loader.conf by itself

That sounds like an acceptable workaround for now. We probably want to 
actually fix nixpkgs at some point, though.

**Comment by notgne2** [comment] 2021-01-11 06:45
Should be fixed now

**Closed by notgne2** 2021-01-11 06:45 UTC
Labels: bug

**Comment by notgne2** [comment] 2023-01-11 01:32
So to update after a long long time, the fix for this is very ugly and kindof sucks, re-activating an older generation still won't update it (because our workaround doesn't even update it, just nukes it so it defaults to newest), and changing any other loader.conf settings won't work either.

The underlying cause also introduces another bug with systemd-initrd

The mentions above pertain to the much delayed real solution to actually get this done with, in case anybody is interested in the progress

**Comment by Shados** [comment] 2023-06-17 08:38
@notgne2 neat to see those merged, but this is still broken for systems using grub. The hacky workaround also doesn't touch grub config, of course.
